
name: fabien_site
description: Site personnel de Fabien Blasquez
publish_to: 'none'

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.2.0
  flutter_web_plugins:
    sdk: flutter
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  visibility_detector: ^0.4.0+2
  url_launcher: ^6.3.1
  http: ^1.2.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/linkedin_174857.png
